name: agc_record
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  audio_waveforms:
  record: ^5.1.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  image_gallery_saver: ^2.0.3
  lottie: ^2.3.2
  intl: ^0.19.0
  another_flushbar: ^1.12.30
  awesome_dialog: ^3.2.1
  logger: ^2.4.0
  audioplayers: ^6.1.0
  just_audio: ^0.9.40
  flutter_ffmpeg: ^0.4.2
  flutter_fft: ^1.0.2+6
  just_waveform: ^0.0.5
  http: ^1.2.2
  http_parser: ^4.0.2
  animated_splash_screen:
  flutter_launcher_icons: "^0.13.1"
  socket_io_client: ^2.0.0
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  ntp: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_agc_record-3.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo_agc_record-3.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo_agc_record-3.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo_agc_record-3.png"

flutter:
  uses-material-design: true

  assets:
    - assets/animation/
    - assets/images/
